# Generated by Django 5.0.6 on 2024-06-19 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=32)),
                ('prenom', models.TextField(max_length=32)),
                ('specialite', models.TextField(max_length=32)),
                ('exercice', models.TextField(max_length=32)),
                ('ug', models.TextField(max_length=32)),
                ('ville', models.TextField(max_length=32)),
                ('adresse', models.TextField(max_length=132, null=True)),
                ('potentiel', models.TextField(max_length=32)),
                ('coeur_de_cibile', models.BooleanField()),
                ('titre', models.TextField(max_length=32)),
                ('frequence', models.IntegerField()),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
