# Generated by Django 5.0.6 on 2024-06-21 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listedoc',
            name='costumer',
        ),
        migrations.CreateModel(
            name='associative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('confirmer', models.BooleanField(default=False)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listeDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listedoc')),
            ],
        ),
    ]
